import "./globals.css";
import Providers from "@/shared/providers/Providers";
import HttpService from "@/services/HttpService";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { HeaderSection } from "@/features/home/components/HeaderSection";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shippivot",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  HttpService.configure();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-center" />
        <Providers>
          <HeaderSection />
          {children}
        </Providers>
      </body>
    </html>
  );
}
