import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { HeaderSection } from "@/components/HeaderSection";
import { AboutSection } from "@/components/AboutSection";
// import { FeaturesSection } from "@/components/FeaturesSection";
// import { MarketplaceSection } from "@/components/MarketPlaceSeaction";
// import { HelpSection } from "@/components/HelpSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shippivot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderSection />
        {children}
        <AboutSection />
        {/* <FeaturesSection />
        <MarketplaceSection />
        <HelpSection /> */}
      </body>
    </html>
  );
}
