import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { HeaderSection } from "@/components/HeaderSection";
import { AboutSection } from "@/components/AboutSection";

import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shippivot",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <HeaderSection />
          {children}
          <AboutSection />
        </Providers>
      </body>
    </html>
  );
}
